//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLogin
    {
        public CustomerLogin(string customerEmail, string password)
        {
            CustomerEmail = customerEmail;
            Password = password;
        }

        public string CustomerEmail { get; set; }
        public string Password { get; set; }
    }
}
