//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.FeedBacks = new HashSet<FeedBack>();
        }
    
        public int BookId { get; set; }
        [Required(ErrorMessage = "Please Enter the Book Name")]
        [Display(Name = "Book Name")]
        public string BookName { get; set; }
        [Required(ErrorMessage = "Please Enter the Author Name")]
        [Display(Name = "Author Name")]
        public string BookAuthor { get; set; }
        [Required(ErrorMessage = "Please Enter the Price of the Book")]
        [Display(Name = "Book Price")]
        public Nullable<double> BookPrice { get; set; }
        [Required(ErrorMessage = "Please Enter the Book Description")]
        [Display(Name = "Book Description")]
        public string BookDescription { get; set; }
        [Required(ErrorMessage = "Please Upload the Book Image")]
        [Display(Name = "Upload Images")]
        public string BookImage { get; set; }
        [Required(ErrorMessage = "Please Enter the Book Quantity")]
        [Display(Name = "Book Quantity")]
        public Nullable<int> BookQuantity { get; set; }
        [Required(ErrorMessage = "Please Enter the Book Category")]
        [Display(Name = "Book Category")]
        public string BookCategory { get; set; }
        [Required(ErrorMessage = "Please Enter the Book Language")]
        [Display(Name = "Book Language")]
        public string BookLanguage { get; set; }
    
        public virtual AddtoCart AddtoCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
