//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.AddtoCarts = new HashSet<AddtoCart>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int CustomerID { get; set; }
        [Required(ErrorMessage = "Please Enter the Name")]
        [Display(Name ="Name")]
        public string CustomerName { get; set; }
        [Required(ErrorMessage="Please Enter the Email ID")]
        [Display(Name = "Email ID")]
        public string CustomerEmail { get; set; }
        [Required(ErrorMessage = "Please Enter the Phone Number")]
        [Display(Name = "Phone Number")]
        public string CustomerPhoneno { get; set; }
        [Required(ErrorMessage = "Please Enter the Address")]
        [Display(Name = "Address")]
        public string CustomerAddress { get; set; }
        [Required(ErrorMessage = "Please Enter the PinCode")]
        [Display(Name = "PinCode")]
        public Nullable<int> CustomerPincode { get; set; }
        [Required(ErrorMessage = "Please Enter the Password")]
        public string Password { get; set; }
        [NotMapped]
        [Compare("Password", ErrorMessage = "Passwords do not match")]
        public string ConfirmPassword { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddtoCart> AddtoCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
