//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int SNo { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Feedback_Description { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
